### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by whoenig** [bitcraze/crazyflie-firmware#286]
Building the latest master version breaks the build using arm-none-eabi-gcc 6.3.1 20170620 on Ubuntu 16.04:

```
src/utils/src/eprintf.c: In function 'evprintf':
src/utils/src/eprintf.c:232:11: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
           if (isdigit((unsigned)*fmt))
           ^~
src/utils/src/eprintf.c:234:13: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
             fmt++;
             ^~~
```

This code was changed/introduced about 5 days ago, see https://github.com/bitcraze/crazyflie-firmware/blame/master/src/utils/src/eprintf.c#L232-L234.

Also, what compiler version is the travis cl using? It should have caught the problem.

**Comment by ataffanel** [comment]
Hi,
This has been fixed this morning in 26a78f87b4b1b and we are updating the docker builder (used in travis) to use the latest arm-none-eabi. Currently travis is using 2016Q2 and this error is found by 2017Q4. It seems that GCC got much better at static analysis lately.
